import type { PlantType, IssueStatus } from "@/types";

export const plantAssetMap: Record<
  PlantType,
  Record<IssueStatus, string> & { label: string; color: string }
> = {
  crystal_bloom: {
    seed: "/plants/crystal_seed.svg",
    sprout: "/plants/crystal_sprout.svg",
    flower: "/plants/crystal_full.svg",
    fruit: "/plants/crystal_full.svg",
    compost: "/plants/crystal_seed.svg",
    label: "Crystal Bloom",
    color: "#6cefff",
  },
  nebula_flower: {
    seed: "/plants/nebula_seed.svg",
    sprout: "/plants/nebula_sprout.svg",
    flower: "/plants/nebula_full.svg",
    fruit: "/plants/nebula_full.svg",
    compost: "/plants/nebula_seed.svg",
    label: "Nebula Flower",
    color: "#9a6cff",
  },
  fire_lily: {
    seed: "/plants/fire_seed.svg",
    sprout: "/plants/fire_sprout.svg",
    flower: "/plants/fire_full.svg",
    fruit: "/plants/fire_full.svg",
    compost: "/plants/fire_seed.svg",
    label: "Fire Lily",
    color: "#ff7d26",
  },
  frost_orchid: {
    seed: "/plants/frost_seed.svg",
    sprout: "/plants/frost_sprout.svg",
    flower: "/plants/frost_full.svg",
    fruit: "/plants/frost_full.svg",
    compost: "/plants/frost_seed.svg",
    label: "Frost Orchid",
    color: "#c7f1ff",
  },
  aurora_blossom: {
    seed: "/plants/aurora_seed.svg",
    sprout: "/plants/aurora_sprout.svg",
    flower: "/plants/aurora_full.svg",
    fruit: "/plants/aurora_full.svg",
    compost: "/plants/aurora_seed.svg",
    label: "Aurora Blossom",
    color: "#34d399",
  },
  ember_dandelion: {
    seed: "/plants/ember_seed.svg",
    sprout: "/plants/ember_sprout.svg",
    flower: "/plants/ember_full.svg",
    fruit: "/plants/ember_full.svg",
    compost: "/plants/ember_seed.svg",
    label: "Ember Dandelion",
    color: "#fb923c",
  },
  moon_petal: {
    seed: "/plants/moon_seed.svg",
    sprout: "/plants/moon_sprout.svg",
    flower: "/plants/moon_full.svg",
    fruit: "/plants/moon_full.svg",
    compost: "/plants/moon_seed.svg",
    label: "Moon Petal",
    color: "#c4b5fd",
  },
  prism_flower: {
    seed: "/plants/prism_seed.svg",
    sprout: "/plants/prism_sprout.svg",
    flower: "/plants/prism_full.svg",
    fruit: "/plants/prism_full.svg",
    compost: "/plants/prism_seed.svg",
    label: "Prism Flower",
    color: "#f472b6",
  },
  thunder_lotus: {
    seed: "/plants/thunder_seed.svg",
    sprout: "/plants/thunder_sprout.svg",
    flower: "/plants/thunder_full.svg",
    fruit: "/plants/thunder_full.svg",
    compost: "/plants/thunder_seed.svg",
    label: "Thunder Lotus",
    color: "#60a5fa",
  },
  void_rose: {
    seed: "/plants/void_seed.svg",
    sprout: "/plants/void_sprout.svg",
    flower: "/plants/void_full.svg",
    fruit: "/plants/void_full.svg",
    compost: "/plants/void_seed.svg",
    label: "Void Rose",
    color: "#a855f7",
  },
} as const;

export const statusScale: Record<IssueStatus, number> = {
  seed: 0.42,
  sprout: 0.52,
  flower: 0.65,
  fruit: 0.76,
  compost: 0.35,
};
