import type { GardenIssue } from "@/types";

export const issues: GardenIssue[] = [
  {
    id: "issue_001",
    title: "AI Onboarding Assistant",
    description: "Build an assistant that helps new users complete workspace setup.",
    status: "sprout",
    priority: "high",
    tags: ["feature", "idea"],
    plantType: "crystal_bloom",
    blockers: ["Needs hallucination eval", "Avoid enterprise SSO path"],
    relatedIssueIds: ["issue_004", "issue_018"],
    isRevived: true,
    niaContextId: "nia_ctx_001",
    contextRoots: [
      {
        title: "March brainstorm",
        sourceType: "doc",
        summary: "Team discussed an onboarding assistant but rejected it due to hallucination risk.",
        relevance: "Similar idea previously explored",
      },
      {
        title: "May customer feedback",
        sourceType: "customer",
        summary: "Multiple customers reported confusion during workspace setup.",
        relevance: "New evidence that revives the idea",
      },
    ],
    suggestedTickets: [
      "Build onboarding Q&A prototype",
      "Create eval set from support docs",
      "Add source citation UI",
    ],
    agentBrief: "Use onboarding docs as the source of truth. Scope to self-serve users only. Include citations and hallucination evals.",
    createdAt: 1737331200000,
    updatedAt: 1746057600000,
  },
  {
    id: "issue_002",
    title: "Semantic Search",
    description: "Replace keyword search with vector-based semantic search.",
    status: "flower",
    priority: "urgent",
    tags: ["feature", "research"],
    plantType: "fire_lily",
    blockers: ["Embedding model selection pending"],
    relatedIssueIds: ["issue_019"],
    isRevived: false,
    contextRoots: [
      {
        title: "Search architecture RFC",
        sourceType: "doc",
        summary: "Proposed pgvector with hybrid BM25 + embedding approach.",
        relevance: "Architecture decision for implementation",
      },
    ],
    suggestedTickets: ["Set up pgvector", "Build embedding pipeline", "Hybrid scoring API"],
    createdAt: 1739145600000,
    updatedAt: 1746489600000,
  },
  {
    id: "issue_003",
    title: "Feedback Loop Automation",
    description: "Automatically route and tag customer feedback to relevant product areas.",
    status: "flower",
    priority: "medium",
    tags: ["feature"],
    plantType: "nebula_flower",
    blockers: [],
    relatedIssueIds: [],
    isRevived: false,
    contextRoots: [],
    suggestedTickets: [],
    createdAt: 1736035200000,
    updatedAt: 1745107200000,
  },
  {
    id: "issue_004",
    title: "Multiplayer Workspace",
    description: "Real-time collaborative editing of workspace configurations.",
    status: "seed",
    priority: "low",
    tags: ["idea", "research"],
    plantType: "frost_orchid",
    blockers: ["Need CRDT vs OT decision"],
    relatedIssueIds: ["issue_001"],
    isRevived: false,
    contextRoots: [
      {
        title: "Figma multiplayer deep-dive",
        sourceType: "research",
        summary: "Figma uses CRDT-based approach for real-time sync with conflict resolution.",
        relevance: "Reference architecture for our implementation",
      },
    ],
    suggestedTickets: [],
    createdAt: 1745884800000,
    updatedAt: 1745884800000,
  },
  {
    id: "issue_005",
    title: "Usage-Based Pricing",
    description: "Pay-as-you-go pricing tier for smaller teams.",
    status: "seed",
    priority: "medium",
    tags: ["idea", "decision"],
    plantType: "crystal_bloom",
    blockers: ["Finance team review needed"],
    relatedIssueIds: [],
    isRevived: false,
    contextRoots: [
      {
        title: "Pricing strategy thread",
        sourceType: "slack",
        summary: "CEO wants to test usage-based model for SMB segment in Q3.",
        relevance: "Executive direction on pricing",
      },
    ],
    suggestedTickets: ["Define usage metrics", "Build metering API", "Stripe usage records integration"],
    createdAt: 1740787200000,
    updatedAt: 1740787200000,
  },
  {
    id: "issue_006",
    title: "Knowledge Base Agent",
    description: "Agent that searches internal docs, Slack, and Notion to answer questions.",
    status: "flower",
    priority: "high",
    tags: ["feature", "research"],
    plantType: "fire_lily",
    blockers: [],
    relatedIssueIds: ["issue_002"],
    isRevived: false,
    contextRoots: [
      {
        title: "Support bot experiment",
        sourceType: "github",
        summary: "Prototype failed because answers were not source-grounded.",
        relevance: "Shows previous failure mode to avoid",
      },
    ],
    suggestedTickets: ["Integrate Notion API", "Build retrieval pipeline", "Add citation rendering"],
    agentBrief: "Ground all answers in retrieved sources. Never generate without citation. Prioritize internal docs over Slack.",
    createdAt: 1740787200000,
    updatedAt: 1746489600000,
  },
  {
    id: "issue_007",
    title: "Custom Dashboard Builder",
    description: "Drag-and-drop dashboards with widgets for metrics and activity feeds.",
    status: "seed",
    priority: "low",
    tags: ["feature", "idea"],
    plantType: "nebula_flower",
    blockers: [],
    relatedIssueIds: [],
    isRevived: false,
    contextRoots: [],
    suggestedTickets: [],
    createdAt: 1746057600000,
    updatedAt: 1746057600000,
  },
  {
    id: "issue_008",
    title: "Critical Security Patch",
    description: "Fix auth token validation vulnerability in API gateway.",
    status: "flower",
    priority: "urgent",
    tags: ["bug"],
    plantType: "frost_orchid",
    blockers: [],
    relatedIssueIds: ["issue_023"],
    isRevived: false,
    contextRoots: [
      {
        title: "Security audit report",
        sourceType: "doc",
        summary: "JWT validation skips expiry check on refresh tokens.",
        relevance: "Root cause identified",
      },
    ],
    suggestedTickets: [],
    createdAt: 1744243200000,
    updatedAt: 1746662400000,
  },
  {
    id: "issue_009",
    title: "Dark Mode Theme",
    description: "Add a full dark mode toggle with system preference detection.",
    status: "flower",
    priority: "medium",
    tags: ["feature"],
    plantType: "void_rose",
    blockers: [],
    relatedIssueIds: [],
    isRevived: false,
    contextRoots: [],
    suggestedTickets: ["CSS custom properties refactor", "Theme toggle component", "System preference detection"],
    createdAt: 1744675200000,
    updatedAt: 1746576000000,
  },
  {
    id: "issue_010",
    title: "Email Notification System",
    description: "Send digest emails for overdue tasks and weekly summaries.",
    status: "seed",
    priority: "high",
    tags: ["feature"],
    plantType: "ember_dandelion",
    blockers: ["Email provider selection"],
    relatedIssueIds: ["issue_022"],
    isRevived: false,
    contextRoots: [],
    suggestedTickets: ["Select email provider", "Build digest template", "Cron job for weekly summary"],
    createdAt: 1746144000000,
    updatedAt: 1746144000000,
  },
  {
    id: "issue_011",
    title: "API Rate Limiting",
    description: "Implement sliding window rate limiting on all public endpoints.",
    status: "flower",
    priority: "high",
    tags: ["feature", "decision"],
    plantType: "thunder_lotus",
    blockers: [],
    relatedIssueIds: [],
    isRevived: false,
    contextRoots: [],
    suggestedTickets: [],
    createdAt: 1742428800000,
    updatedAt: 1746576000000,
  },
  {
    id: "issue_012",
    title: "Accessibility Audit",
    description: "Full WCAG 2.1 AA audit and remediation of all user-facing pages.",
    status: "sprout",
    priority: "medium",
    tags: ["research"],
    plantType: "aurora_blossom",
    blockers: ["Waiting for audit vendor report"],
    relatedIssueIds: [],
    isRevived: false,
    contextRoots: [
      {
        title: "Accessibility vendor proposal",
        sourceType: "doc",
        summary: "Vendor will deliver full audit by end of May. Focus on keyboard nav and screen readers.",
        relevance: "Scoping the remediation work",
      },
    ],
    suggestedTickets: ["Fix keyboard navigation", "Add ARIA labels", "Color contrast fixes"],
    createdAt: 1743465600000,
    updatedAt: 1746489600000,
  },
  {
    id: "issue_013",
    title: "Mobile Responsive Redesign",
    description: "Redesign all views for mobile-first responsive layouts.",
    status: "seed",
    priority: "low",
    tags: ["feature", "idea"],
    plantType: "moon_petal",
    blockers: [],
    relatedIssueIds: [],
    isRevived: false,
    contextRoots: [],
    suggestedTickets: [],
    createdAt: 1746489600000,
    updatedAt: 1746489600000,
  },
  {
    id: "issue_014",
    title: "Data Export Pipeline",
    description: "Allow users to export all their data as CSV/JSON with one click.",
    status: "seed",
    priority: "low",
    tags: ["feature"],
    plantType: "prism_flower",
    blockers: [],
    relatedIssueIds: [],
    isRevived: false,
    contextRoots: [],
    suggestedTickets: [],
    createdAt: 1746662400000,
    updatedAt: 1746662400000,
  },
  {
    id: "issue_015",
    title: "Login Page Broken on Safari",
    description: "Users on Safari 17 get a blank white screen after entering credentials. No error logged.",
    status: "flower",
    priority: "urgent",
    tags: ["bug"],
    plantType: "fire_lily",
    blockers: ["Cannot reproduce locally"],
    relatedIssueIds: [],
    isRevived: false,
    contextRoots: [
      {
        title: "Safari 17 WebKit changelog",
        sourceType: "research",
        summary: "Safari 17 changed cookie partitioning behavior which may affect auth flow.",
        relevance: "Likely root cause",
      },
    ],
    suggestedTickets: ["Set up Safari BrowserStack testing", "Fix cookie SameSite attribute"],
    createdAt: 1746662400000,
    updatedAt: 1746748800000,
  },
  {
    id: "issue_016",
    title: "Database Connection Pool Exhaustion",
    description: "Production DB hits max connections during peak hours causing 502 errors for ~5% of requests.",
    status: "seed",
    priority: "urgent",
    tags: ["bug"],
    plantType: "thunder_lotus",
    blockers: [],
    relatedIssueIds: [],
    isRevived: false,
    contextRoots: [
      {
        title: "PgBouncer monitoring dashboard",
        sourceType: "doc",
        summary: "Peak connection count exceeds pool max by 40% during 2-4pm UTC.",
        relevance: "Data showing the problem scope",
      },
    ],
    suggestedTickets: ["Add PgBouncer", "Audit long-running queries", "Add connection timeout"],
    createdAt: 1746748800000,
    updatedAt: 1746748800000,
  },
  {
    id: "issue_017",
    title: "Stripe Webhook Failures",
    description: "Payment webhooks silently failing for subscription renewals. Revenue leaking since last deploy.",
    status: "flower",
    priority: "urgent",
    tags: ["bug"],
    plantType: "ember_dandelion",
    blockers: [],
    relatedIssueIds: [],
    isRevived: false,
    contextRoots: [
      {
        title: "Stripe dashboard logs",
        sourceType: "doc",
        summary: "Webhook endpoint returning 500 on checkout.session.completed events since deploy v2.14.",
        relevance: "Pinpoints the regression",
      },
    ],
    suggestedTickets: ["Fix webhook signature validation", "Add webhook retry queue", "Backfill missed renewals"],
    createdAt: 1746576000000,
    updatedAt: 1746748800000,
  },
  {
    id: "issue_018",
    title: "Onboarding Drop-off at Step 3",
    description: "Analytics show 62% of new users abandon onboarding at the team invite step. Need to simplify.",
    status: "seed",
    priority: "high",
    tags: ["research", "decision"],
    plantType: "aurora_blossom",
    blockers: [],
    relatedIssueIds: ["issue_001"],
    isRevived: false,
    contextRoots: [
      {
        title: "Mixpanel funnel report",
        sourceType: "customer",
        summary: "62% drop-off at team invite step. Users who skip it have 3x lower retention.",
        relevance: "Key metric driving urgency",
      },
    ],
    suggestedTickets: ["A/B test skip-invite flow", "Simplify invite UI", "Add solo-user path"],
    createdAt: 1746403200000,
    updatedAt: 1746403200000,
  },
  {
    id: "issue_019",
    title: "Search Returns Stale Results",
    description: "Search index not updating after edits. Users see deleted items in results for up to 30 minutes.",
    status: "sprout",
    priority: "high",
    tags: ["bug"],
    plantType: "crystal_bloom",
    blockers: [],
    relatedIssueIds: ["issue_002"],
    isRevived: false,
    contextRoots: [],
    suggestedTickets: ["Add real-time index invalidation", "Reduce reindex interval to 1 min"],
    createdAt: 1745884800000,
    updatedAt: 1746662400000,
  },
  {
    id: "issue_020",
    title: "CSV Import Crashes on Large Files",
    description: "Importing CSVs over 10MB causes OOM crash in the worker. Need streaming parser.",
    status: "seed",
    priority: "medium",
    tags: ["bug"],
    plantType: "void_rose",
    blockers: [],
    relatedIssueIds: [],
    isRevived: false,
    contextRoots: [],
    suggestedTickets: ["Replace Papa Parse with streaming parser", "Add file size validation"],
    createdAt: 1746230400000,
    updatedAt: 1746230400000,
  },
  {
    id: "issue_021",
    title: "Timezone Display Bug",
    description: "All dates show in UTC instead of user's local timezone. Confusing for international teams.",
    status: "flower",
    priority: "medium",
    tags: ["bug"],
    plantType: "moon_petal",
    blockers: [],
    relatedIssueIds: [],
    isRevived: false,
    contextRoots: [],
    suggestedTickets: [],
    createdAt: 1745107200000,
    updatedAt: 1746576000000,
  },
  {
    id: "issue_022",
    title: "Duplicate Notification Spam",
    description: "Users receiving 3-4 duplicate push notifications per event. Idempotency key not working.",
    status: "sprout",
    priority: "high",
    tags: ["bug"],
    plantType: "frost_orchid",
    blockers: [],
    relatedIssueIds: ["issue_010"],
    isRevived: false,
    contextRoots: [
      {
        title: "Notification service logs",
        sourceType: "doc",
        summary: "Idempotency key uses event_id but multiple workers process same event from queue.",
        relevance: "Root cause: missing dedup at queue level",
      },
    ],
    suggestedTickets: ["Add SQS deduplication ID", "Fix idempotency key scope"],
    createdAt: 1746057600000,
    updatedAt: 1746662400000,
  },
  {
    id: "issue_023",
    title: "Role Permissions Not Enforced",
    description: "Viewer-role users can edit documents via direct API calls. Frontend hides buttons but backend allows it.",
    status: "seed",
    priority: "urgent",
    tags: ["bug"],
    plantType: "void_rose",
    blockers: [],
    relatedIssueIds: ["issue_008"],
    isRevived: false,
    contextRoots: [],
    suggestedTickets: ["Add middleware permission checks", "Audit all write endpoints"],
    createdAt: 1746748800000,
    updatedAt: 1746748800000,
  },
  {
    id: "issue_024",
    title: "Memory Leak in Real-time Sync",
    description: "WebSocket connections not cleaned up on tab close. Server memory grows 200MB/day.",
    status: "sprout",
    priority: "medium",
    tags: ["bug"],
    plantType: "nebula_flower",
    blockers: [],
    relatedIssueIds: [],
    isRevived: false,
    contextRoots: [],
    suggestedTickets: ["Add connection cleanup on disconnect", "Implement heartbeat ping"],
    createdAt: 1745539200000,
    updatedAt: 1746576000000,
  },
  {
    id: "issue_025",
    title: "Billing Page Slow Load",
    description: "Billing history page takes 8+ seconds to load. N+1 query on invoice line items.",
    status: "flower",
    priority: "low",
    tags: ["bug"],
    plantType: "prism_flower",
    blockers: [],
    relatedIssueIds: [],
    isRevived: false,
    contextRoots: [],
    suggestedTickets: [],
    createdAt: 1744243200000,
    updatedAt: 1746316800000,
  },
  {
    id: "issue_026",
    title: "Image Upload Corrupts on Resize",
    description: "PNG uploads with transparency lose alpha channel during thumbnail generation.",
    status: "seed",
    priority: "low",
    tags: ["bug"],
    plantType: "frost_orchid",
    blockers: [],
    relatedIssueIds: [],
    isRevived: false,
    contextRoots: [],
    suggestedTickets: ["Switch to sharp with alpha preservation"],
    createdAt: 1746576000000,
    updatedAt: 1746576000000,
  },
];
