import type { Seed } from "@/types";

export const seeds: Seed[] = [
  {
    id: "s1",
    title: "AI Onboarding Assistant",
    description: "An AI-powered assistant that guides new users through product setup.",
    status: "growing",
    priority: "high",
    plantType: "crystal_bloom",
    created_at: "2026-01-20T00:00:00Z",
    updated_at: "2026-05-01T00:00:00Z",
  },
  {
    id: "s2",
    title: "Semantic Search",
    description: "Replace keyword search with vector-based semantic search.",
    status: "growing",
    priority: "urgent",
    plantType: "fire_lily",
    created_at: "2026-02-10T00:00:00Z",
    updated_at: "2026-05-05T00:00:00Z",
  },
  {
    id: "s3",
    title: "Feedback Loop Automation",
    description: "Automatically route and tag customer feedback to relevant product areas.",
    status: "blooming",
    priority: "medium",
    plantType: "nebula_flower",
    created_at: "2026-01-05T00:00:00Z",
    updated_at: "2026-04-20T00:00:00Z",
  },
  {
    id: "s4",
    title: "Multiplayer Workspace",
    description: "Real-time collaborative editing of workspace configurations.",
    status: "seed",
    priority: "low",
    plantType: "frost_orchid",
    created_at: "2026-04-28T00:00:00Z",
    updated_at: "2026-04-28T00:00:00Z",
  },
  {
    id: "s5",
    title: "Usage-Based Pricing",
    description: "Pay-as-you-go pricing tier for smaller teams.",
    status: "seed",
    priority: "medium",
    plantType: "crystal_bloom",
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "s6",
    title: "Knowledge Base Agent",
    description: "Agent that searches internal docs, Slack, and Notion to answer questions.",
    status: "growing",
    priority: "high",
    plantType: "fire_lily",
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-05-05T00:00:00Z",
  },
  {
    id: "s7",
    title: "Custom Dashboard Builder",
    description: "Drag-and-drop dashboards with widgets for metrics and activity feeds.",
    status: "seed",
    priority: "low",
    plantType: "nebula_flower",
    created_at: "2026-05-01T00:00:00Z",
    updated_at: "2026-05-01T00:00:00Z",
  },
  {
    id: "s8",
    title: "Critical Security Patch",
    description: "Fix auth token validation vulnerability in API gateway.",
    status: "blooming",
    priority: "urgent",
    plantType: "frost_orchid",
    created_at: "2026-04-10T00:00:00Z",
    updated_at: "2026-05-08T00:00:00Z",
  },
  {
    id: "s9",
    title: "Dark Mode Theme",
    description: "Add a full dark mode toggle with system preference detection.",
    status: "growing",
    priority: "medium",
    plantType: "void_rose",
    created_at: "2026-04-15T00:00:00Z",
    updated_at: "2026-05-06T00:00:00Z",
  },
  {
    id: "s10",
    title: "Email Notification System",
    description: "Send digest emails for overdue tasks and weekly summaries.",
    status: "seed",
    priority: "high",
    plantType: "ember_dandelion",
    created_at: "2026-05-02T00:00:00Z",
    updated_at: "2026-05-02T00:00:00Z",
  },
  {
    id: "s11",
    title: "API Rate Limiting",
    description: "Implement sliding window rate limiting on all public endpoints.",
    status: "blooming",
    priority: "high",
    plantType: "thunder_lotus",
    created_at: "2026-03-20T00:00:00Z",
    updated_at: "2026-05-07T00:00:00Z",
  },
  {
    id: "s12",
    title: "Accessibility Audit",
    description: "Full WCAG 2.1 AA audit and remediation of all user-facing pages.",
    status: "growing",
    priority: "medium",
    plantType: "aurora_blossom",
    created_at: "2026-04-01T00:00:00Z",
    updated_at: "2026-05-05T00:00:00Z",
  },
  {
    id: "s13",
    title: "Mobile Responsive Redesign",
    description: "Redesign all views for mobile-first responsive layouts.",
    status: "seed",
    priority: "low",
    plantType: "moon_petal",
    created_at: "2026-05-06T00:00:00Z",
    updated_at: "2026-05-06T00:00:00Z",
  },
  {
    id: "s14",
    title: "Data Export Pipeline",
    description: "Allow users to export all their data as CSV/JSON with one click.",
    status: "seed",
    priority: "low",
    plantType: "prism_flower",
    created_at: "2026-05-08T00:00:00Z",
    updated_at: "2026-05-08T00:00:00Z",
  },
  {
    id: "s15",
    title: "Login Page Broken on Safari",
    description: "Users on Safari 17 get a blank white screen after entering credentials. No error logged.",
    status: "growing",
    priority: "urgent",
    plantType: "fire_lily",
    created_at: "2026-05-08T00:00:00Z",
    updated_at: "2026-05-09T00:00:00Z",
  },
  {
    id: "s16",
    title: "Database Connection Pool Exhaustion",
    description: "Production DB hits max connections during peak hours causing 502 errors for ~5% of requests.",
    status: "seed",
    priority: "urgent",
    plantType: "thunder_lotus",
    created_at: "2026-05-09T00:00:00Z",
    updated_at: "2026-05-09T00:00:00Z",
  },
  {
    id: "s17",
    title: "Stripe Webhook Failures",
    description: "Payment webhooks silently failing for subscription renewals. Revenue leaking since last deploy.",
    status: "growing",
    priority: "urgent",
    plantType: "ember_dandelion",
    created_at: "2026-05-07T00:00:00Z",
    updated_at: "2026-05-09T00:00:00Z",
  },
  {
    id: "s18",
    title: "Onboarding Drop-off at Step 3",
    description: "Analytics show 62% of new users abandon onboarding at the team invite step. Need to simplify.",
    status: "seed",
    priority: "high",
    plantType: "aurora_blossom",
    created_at: "2026-05-05T00:00:00Z",
    updated_at: "2026-05-05T00:00:00Z",
  },
  {
    id: "s19",
    title: "Search Returns Stale Results",
    description: "Search index not updating after edits. Users see deleted items in results for up to 30 minutes.",
    status: "growing",
    priority: "high",
    plantType: "crystal_bloom",
    created_at: "2026-04-28T00:00:00Z",
    updated_at: "2026-05-08T00:00:00Z",
  },
  {
    id: "s20",
    title: "CSV Import Crashes on Large Files",
    description: "Importing CSVs over 10MB causes OOM crash in the worker. Need streaming parser.",
    status: "seed",
    priority: "medium",
    plantType: "void_rose",
    created_at: "2026-05-03T00:00:00Z",
    updated_at: "2026-05-03T00:00:00Z",
  },
  {
    id: "s21",
    title: "Timezone Display Bug",
    description: "All dates show in UTC instead of user's local timezone. Confusing for international teams.",
    status: "blooming",
    priority: "medium",
    plantType: "moon_petal",
    created_at: "2026-04-20T00:00:00Z",
    updated_at: "2026-05-07T00:00:00Z",
  },
  {
    id: "s22",
    title: "Duplicate Notification Spam",
    description: "Users receiving 3-4 duplicate push notifications per event. Idempotency key not working.",
    status: "growing",
    priority: "high",
    plantType: "frost_orchid",
    created_at: "2026-05-01T00:00:00Z",
    updated_at: "2026-05-08T00:00:00Z",
  },
  {
    id: "s23",
    title: "Role Permissions Not Enforced",
    description: "Viewer-role users can edit documents via direct API calls. Frontend hides buttons but backend allows it.",
    status: "seed",
    priority: "urgent",
    plantType: "void_rose",
    created_at: "2026-05-09T00:00:00Z",
    updated_at: "2026-05-09T00:00:00Z",
  },
  {
    id: "s24",
    title: "Memory Leak in Real-time Sync",
    description: "WebSocket connections not cleaned up on tab close. Server memory grows 200MB/day.",
    status: "growing",
    priority: "medium",
    plantType: "nebula_flower",
    created_at: "2026-04-25T00:00:00Z",
    updated_at: "2026-05-06T00:00:00Z",
  },
  {
    id: "s25",
    title: "Billing Page Slow Load",
    description: "Billing history page takes 8+ seconds to load. N+1 query on invoice line items.",
    status: "blooming",
    priority: "low",
    plantType: "prism_flower",
    created_at: "2026-04-10T00:00:00Z",
    updated_at: "2026-05-04T00:00:00Z",
  },
  {
    id: "s26",
    title: "Image Upload Corrupts on Resize",
    description: "PNG uploads with transparency lose alpha channel during thumbnail generation.",
    status: "seed",
    priority: "low",
    plantType: "frost_orchid",
    created_at: "2026-05-07T00:00:00Z",
    updated_at: "2026-05-07T00:00:00Z",
  },
];
